#!/usr/bin/env bash

# Generate PNG icons based on the Calendly colors

# requires `brew install librsvg`

# From Calendly
colors=(
  ee5353
  f778b4
  e27eff
  8989fc
  4a91e9
  0cc0d7
  34c76e
  67c820
  dfc12d
  f49a31
)

d=256
r=$((d / 2))

svg() {
  echo -n '<svg xmlns="http://www.w3.org/2000/svg" height="'"$d"'" width="'"$d"'" ><circle fill="#'"$1"'" cx="'"$r"'" cy="'"$r"'" r="'"$r"'"></circle></svg>'
}

mkdir -p icons

for color in "${colors[@]}"; do
  rsvg-convert -h 256 <(svg "$color") > "icons/event-type-color-$color.png"
done
