#!/usr/bin/env bash

# Generate PNG icons based on the Calendly colors

# requires `brew install librsvg`

# From Calendly
colors=(
  ee5353
  f778b4
  e27eff
  8989fc
  4a91e9
  0cc0d7
  34c76e
  67c820
  dfc12d
  f49a31
)

svg() {
  echo "
    <svg viewBox='0 0 2 2'>
      <circle fill='#$1' cx='1' cy='1' r='1'/>
    </svg>
  "
}

mkdir -p icons

for color in "${colors[@]}"; do
  rsvg-convert -h 256 <(svg "$color") > "icons/event-type-color-$color.png"
done
